services:
  postgres:
    image: postgres:15.3
    container_name: bmfbovespa
    restart: always
    env_file:
      - .env 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${EXTERNAL_PORT}:${POSTGRES_PORT}"
    command: ["postgres", "-p", "${POSTGRES_PORT}"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: